-- Create sipay_panel_fatura table for tracking Sipay payments
CREATE TABLE sipay_panel_fatura (
    id INT AUTO_INCREMENT PRIMARY KEY,
    invoice_id VARCHAR(100) NOT NULL UNIQUE COMMENT 'Sipay invoice ID',
    cc_holder_name VARCHAR(100) NOT NULL COMMENT 'Kart sahibi adı',
    cc_no VARCHAR(20) NOT NULL COMMENT 'Kart numarası',
    expiry_month VARCHAR(2) NOT NULL COMMENT 'Son kullanma ayı',
    expiry_year VARCHAR(4) NOT NULL COMMENT 'Son kullanma yılı',
    cvv VARCHAR(4) NOT NULL COMMENT 'CVV kodu',
    total DECIMAL(10,2) NOT NULL COMMENT 'Toplam tutar',
    quantity INT DEFAULT 1 COMMENT 'Miktar',
    name VARCHAR(100) NOT NULL COMMENT 'Müşteri adı',
    surname VARCHAR(100) NOT NULL COMMENT 'Müşteri soyadı',
    currency_code VARCHAR(3) DEFAULT 'TRY' COMMENT 'Para birimi',
    installments_number VARCHAR(2) DEFAULT '1' COMMENT 'Taksit sayısı',
    invoice_description TEXT COMMENT 'Fatura açıklaması',
    bill_email VARCHAR(100) COMMENT 'Fatura e-posta',
    bill_phone VARCHAR(20) COMMENT 'Fatura telefon',
    bill_address1 TEXT COMMENT 'Fatura adres 1',
    bill_address2 TEXT COMMENT 'Fatura adres 2',
    bill_city VARCHAR(50) COMMENT 'Fatura şehir',
    bill_postcode VARCHAR(10) COMMENT 'Fatura posta kodu',
    bill_state VARCHAR(50) COMMENT 'Fatura eyalet/il',
    bill_country VARCHAR(50) COMMENT 'Fatura ülke',
    ip VARCHAR(45) COMMENT 'IP adresi',
    status TINYINT DEFAULT 0 COMMENT 'Durum: 0=beklemede, 1=başarılı, 2=başarısız',
    unit_price DECIMAL(10,2) COMMENT 'Birim fiyat',
    bayi_id INT COMMENT 'Bayi ID',
    transaction_id VARCHAR(100) COMMENT 'Sipay transaction ID',
    sipay_status VARCHAR(10) COMMENT 'Sipay durum kodu',
    error_code VARCHAR(10) COMMENT 'Hata kodu',
    error_message TEXT COMMENT 'Hata mesajı',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'Oluşturulma tarihi',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Güncellenme tarihi',
    INDEX idx_invoice_id (invoice_id),
    INDEX idx_bayi_id (bayi_id),
    INDEX idx_status (status),
    INDEX idx_created_at (created_at),
    INDEX idx_transaction_id (transaction_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT 'Sipay panel fatura takibi için kullanılan tablo'; 