import React, { createContext, useContext, useState, useEffect } from 'react';
import { useAuth } from '@/hooks/use-auth';

type Language = 'tr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  tr: {
    'dashboard': 'Panel',
    'vin-hacker': 'VIN Hacker',
    'kilometre-hacker': 'Kilometre Hacker',
    'reports': 'Raporlar',
    'settings': 'Ayarlar',
    'test-date': 'Test Tarihi',
    'company': 'Firma',
    'companies': 'Firmalar',
    'dealer': 'Bayi',
    'dealers': 'Bayiler',
    'module': 'Modul',
    'kilometre': 'Kilometre',
    'details': 'Detay',
    'download': 'İndir',
    'close': 'Kapat',
    'save': 'Kaydet',
    'cancel': 'İptal',
    'edit': 'Düzenle',
    'delete': 'Sil',
    'add': 'Ekle',
    'search': 'Ara',
    'filter': 'Filtrele',
    'export': 'Dışa Aktar',
    'import': 'İçe Aktar',
    'refresh': 'Yenile',
    'loading': 'Yükleniyor...',
    'error': 'Hata',
    'success': 'Başarılı',
    'warning': 'Uyarı',
    'info': 'Bilgi',
    'confirm': 'Onayla',
    'yes': 'Evet',
    'no': 'No',
    'ok': 'Tamam',
    'back': 'Geri',
    'next': 'İleri',
    'previous': 'Önceki',
    'first': 'İlk',
    'last': 'Son',
    'page': 'Sayfa',
    'of': 'of',
    'total': 'Toplam',
    'items': 'öğe',
    'per-page': 'Sayfa başına',
    'showing': 'Gösteriliyor',
    'to': 'ile',
    'entries': 'kayıt',
    'no-data': 'Veri bulunamadı',
    'no-results': 'Sonuç bulunamadı',
    'try-again': 'Tekrar dene',
    'contact-support': 'Destek ile iletişime geç',
    'language': 'Dil',
    'turkish': 'Türkçe',
    'english': 'İngilizce',
    'dashboard-description': 'Sistem yönetimi ve istatistikleri burada görüntüleyebilirsiniz.',
    'total-commission': 'Toplam Komisyon',
    'device-sales-total': 'Cihaz Satış Toplamı',
    'total-km-test': 'Toplam Km Test',
    'active-dealers': 'Aktif Bayiler',
    'total-balance': 'Toplam Bakiye',
    'total-test-fee': 'Toplam Test Ücreti',
    'active-companies': 'Aktif Firmalar',
    'total-vin-test': 'Toplam VIN Test',
    'panel-users': 'Panel Kullanıcıları',
    'program-users': 'Program Kullanıcıları',
    'balance-management': 'Bakiye Yönetimi',
    'commission-management': 'Komisyon Yönetimi',
    'buy-device': 'Cihaz Satın Al',
    'roles': 'Roller',
    'blog': 'Blog',
    'logout': 'Çıkış Yap',
    'device-sales': 'Cihaz Satışları',
    'add-company': 'Yeni Firma Ekle',
    'no-companies-found': 'Henüz firma bulunmuyor',
    'error-loading-companies': 'Firma verileri yüklenirken bir hata oluştu',
    'company-name': 'Firma Adı',
    'company-title': 'Firma Ünvanı',
    'email': 'E-posta',
    'phone': 'Telefon',
    'tax-office': 'Vergi Dairesi',
    'tax-number': 'Vergi No',
    'status': 'Durum',
    'active': 'Aktif',
    'inactive': 'Pasif',
    'companies-description': 'Firmaları görüntüle, düzenle ve yönet',
    'select-filter': 'Filtre seçin',
    'search-by-company-title': 'Firma ünvanı ile ara...',
    'search-by-tax-number': 'Vergi no ile ara...',
    'number': 'No',
    'created-at': 'Oluşturulma',
    'actions': 'İşlemler',
    'error-deleting-company': 'Firma silinirken bir hata oluştu',
    'company-deleted-successfully': 'Firma başarıyla silindi',
    'error-loading-data': 'Veri yüklenirken bir hata oluştu',
    'add-new-company': 'Yeni Firma Ekle',
    'add-company-description': 'Firma bilgilerini girerek yeni bir firma ekleyebilirsiniz.',
    'company-added-successfully': 'Firma başarıyla eklendi',
    'enter-company-name': 'Firma adı giriniz',
    'enter-company-title': 'Firma ünvanı giriniz',
    'enter-email-address': 'Email adresi giriniz',
    'enter-phone-number': 'Telefon numarası giriniz',
    'enter-tax-office': 'Vergi dairesi giriniz',
    'enter-tax-number': 'Vergi numarası giriniz',
    'tc-number': 'TC No',
    'enter-tc-number': 'TC kimlik numarası giriniz',
    'address': 'Adres',
    'enter-address': 'Adres giriniz',
    'iban': 'IBAN',
    'enter-iban-number': 'IBAN numarası giriniz',
    'adding': 'Ekleniyor...',
    'dealers-description': 'Sistemde kayıtlı tüm bayilerin listesi',
    'api-request-failed': 'API isteği başarısız oldu',
    'error-deleting-dealer': 'Bayi silme işlemi başarısız oldu',
    'dealer-deleted-successfully': 'Bayi başarıyla silindi',
    'search-by-name-or-contact': 'İsim veya iletişim bilgileri ile ara...',
    'select-status': 'Durum Seçin',
    'all': 'Tümü',
    'select-company': 'Firma Seçin',
    'all-companies': 'Tüm Firmalar',
    'add-dealer': 'Bayi Ekle',
    'dealer-name': 'Bayi Adı',
    'city-district': 'İl/İlçe',
    'dealer-rate': 'Bayi Oranı',
    'no-dealers-found-matching-criteria': 'Arama kriterlerine uygun bayi bulunamadı',
    'no-dealers-found': 'Kayıtlı bayi bulunamadı',
    'delete-dealer': 'Bayiyi Sil',
    'delete-dealer-confirmation': 'Bu bayiyi silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.',
    'edit-company': 'Firma Düzenle',
    'error-updating-company': 'Firma güncellenirken bir hata oluştu',
    'company-updated-successfully': 'Firma başarıyla güncellendi',
    'updating': 'Güncelleniyor...',
    'update': 'Güncelle',
    'delete-company': 'Firmayı silmek istediğinize emin misiniz?',
    'delete-company-confirmation': 'Bu işlem geri alınamaz. Firma ve ilişkili tüm veriler kalıcı olarak silinecektir.',
    'deleting': 'Siliniyor...',
    'edit-dealer': 'Bayi Düzenle',
    'add-new-dealer': 'Yeni Bayi Ekle',
    'fill-dealer-info-completely': 'Bayi bilgilerini eksiksiz doldurunuz',
    'dealer-operation-failed': 'Bayi işlemi başarısız oldu',
    'dealer-updated-successfully': 'Bayi başarıyla güncellendi',
    'dealer-added-successfully': 'Bayi başarıyla eklendi',
    'operation-failed': 'İşlem başarısız',
    'city': 'İl',
    'district': 'İlçe',
    'select-city': 'İl Seçiniz',
    'select-district': 'İlçe Seçiniz',
    'select-city-first': 'Önce il seçiniz',
    'no-districts-found': 'İlçe bulunamadı',
    'saving': 'Kaydediliyor...',
    'test-based-balance-management-system': 'Test bazlı bakiye yönetimi sistemi',
    'load-balance': 'Bakiye Yükle',
    'online-payment-sipay': 'Online Ödeme Sipay',
    'balance-history': 'Bakiye Geçmişi',
    'balance-loading-completed-successfully': 'Bakiye yükleme işlemi başarıyla tamamlandı',
    'error-during-balance-loading': 'Bakiye yükleme işlemi sırasında bir hata oluştu',
    'please-fill-all-fields': 'Lütfen tüm alanları doldurun',
    'enter-valid-amount': 'Geçerli bir miktar giriniz',
    'you-can-load-balance-by-selecting-dealer': 'Bayi seçerek bakiye yüklemesi yapabilirsiniz',
    'select-dealer': 'Bayi Seçiniz',
    'select-company-first': 'Önce firma seçiniz',
    'amount-to-load': 'Yüklenecek Tutar',
    'enter-amount': 'Tutar giriniz',
    'online-balance-loading-sipay': 'Online Bakiye Yükleme Sipay',
    'you-can-load-balance-with-sipay-secure-payment': 'Sipay güvenli ödeme altyapısı ile bakiye yükleyebilirsiniz',
    'amount': 'Tutar',
    'processing': 'İşleniyor...',
    'make-payment': 'Ödeme Yap',
    'error-during-payment-process': 'Ödeme işlemi başlatılırken bir hata oluştu',
    'balance-transactions': 'Bakiye İşlemleri',
    'date': 'Tarih',
    'transaction-detail': 'İşlem Detayı',
    'description': 'Açıklama',
    'balance': 'Bakiye',
    'manual-balance-loading': 'Manuel Bakiye Yükleme',
    'iyzico-balance-loading': 'iyzico Bakiye Yükleme',
    'sipay-balance-loading': 'Sipay Bakiye Yükleme',
    'no-transactions-found': 'İşlem bulunamadı',
    'view-edit-and-manage-commission-management': 'Komisyon Yönetimini görüntüle, düzenle ve yönet',
    'test-id': 'Test ID',
    'dealer-rate-percentage': 'Bayi Oranı (%)',
    'fee': 'Ücret',
    'test-commission-amount': 'Test Komisyon Tutarı',
    'commission-amount': 'Komisyon Tutarı',
    'filtering-successful': 'Filtreleme başarılı',
    'error-during-filtering': 'Filtreleme sırasında bir hata oluştu',
        'no-records-found': 'Kayıt bulunamadı',
        'records': 'kayıt',
        'range': 'arası',
        'view-edit-and-manage-panel-users': 'Panel kullanıcılarını görüntüle, düzenle ve yönet',
        'search-by-name-or-email': 'İsim veya e-posta ile ara...',
        'select-role': 'Rol Seç',
        'all-roles': 'Tüm Roller',
        'add-user': 'Kullanıcı Ekle',
        'name': 'Ad',
        'role': 'Rol',
        'no-users-found-matching-criteria': 'Arama kriterlerine uygun kullanıcı bulunamadı',
        'no-users-found': 'Kullanıcı bulunamadı',
        'user-deleted-successfully': 'Kullanıcı başarıyla silindi',
        'error-deleting-user': 'Kullanıcı silinirken bir hata oluştu',
        'delete-user': 'Kullanıcıyı Sil',
        'delete-user-confirmation': 'Bu kullanıcıyı silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.',
        'panel-user': 'Panel Kullanıcı',
        'fill-required-information-for-panel-user': 'Panel kullanıcısı için gerekli bilgileri eksiksiz doldurun.',
        'full-name': 'Ad Soyad',
        'password': 'Şifre',
        'leave-empty-to-keep-current': 'Boş bırakılırsa değişmez',
        'language-preference': 'Dil Tercihi',
        'select-language': 'Dil Seçiniz',
        'user-updated-successfully': 'Kullanıcı başarıyla güncellendi',
        'user-added-successfully': 'Kullanıcı başarıyla eklendi',
        'view-edit-and-manage-program-users': 'Program kullanıcılarını görüntüle, düzenle ve yönet',
        'search-by-name-or-mac': 'İsim veya MAC adresi ile ara...',
        'all-dealers': 'Tüm Bayiler',
        'add-program-user': 'Program Kullanıcı Ekle',
        'mac-address': 'MAC Adresi',
        'first-login': 'İlk Giriş',
        'no-program-users-found-matching-criteria': 'Arama kriterlerine uygun program kullanıcısı bulunamadı',
        'no-program-users-found': 'Program kullanıcısı bulunamadı',
        'program-user-deleted-successfully': 'Program kullanıcısı başarıyla silindi',
        'error-deleting-program-user': 'Program kullanıcısı silinirken bir hata oluştu',
        'fill-program-user-info-completely': 'Lütfen program kullanıcı bilgilerini eksiksiz ve doğru doldurunuz',
        'enter-password': 'Şifre giriniz',
        'enter-new-password': 'Yeni şifre giriniz',
        'done': 'Yapıldı',
        'not-done': 'Yapılmadı',
        'program-user-updated-successfully': 'Program kullanıcısı güncellendi',
        'program-user-added-successfully': 'Program kullanıcısı eklendi',
        'cannot-delete-user-with-tests': 'Bu kullanıcının VIN testleri bulunduğu için silinemez. Önce testleri silin veya kullanıcıyı pasif yapın.',
        'user-has-related-data': 'Bu kullanıcının ilişkili verileri bulunduğu için silinemez.',
        'vehicle-mileage-query-operations': 'Araç kilometre sorgulama işlemlerini buradan gerçekleştirebilirsiniz',
        'start-date': 'Başlangıç Tarihi',
        'end-date': 'Bitiş Tarihi',
        'query': 'Sorgula',
        'plate-model': 'Plaka/Model',
        'plate': 'Plaka',
        'brand-model': 'Marka/Model',
        'search-by-plate': 'Plaka ile ara...',
        'search-by-brand-model': 'Marka/Model ile ara...',
        'chassis-number': 'Şase No',
        'engine-number': 'Motor No',
        'odometer-km': 'Gösterge KM',
        'no-records-found-matching-criteria': 'Arama kriterlerine uygun kayıt bulunamadı',
        'date-range': 'Tarih Aralığı',
        'test-report': 'Test Raporu',
        'vehicle-information': 'Araç Bilgileri',
        'test-details': 'Test Detayları',
        'download-pdf': 'PDF İndir',
        'test-type': 'Test Tipi',
        'test-details-could-not-be-loaded': 'Test detayları yüklenemedi',
        'model-year': 'Model Yılı',
        'user': 'Kullanıcı',
        'vehicle-vin-and-mileage-query-operations': 'Araç VIN ve kilometre sorgulama işlemlerini buradan gerçekleştirebilirsiniz',
        'device-sales-management-and-tracking': 'Cihaz satış yönetimi ve takibi',
        'new-sale': 'Yeni Satış',
        'new-device-sale': 'Yeni Cihaz Satışı',
        'edit-device-sale': 'Cihaz Satışını Düzenle',
        'enter-device-sale-information': 'Cihaz satış bilgilerini girin',
        'total-amount': 'Toplam Tutar',
        'enter-total-amount': 'Toplam tutar giriniz',
        'paid-amount': 'Ödenen Tutar',
        'enter-paid-amount': 'Ödenen tutar giriniz',
        'payment-date': 'Ödeme Tarihi',
        'remaining-payment-date': 'Kalan Ödeme Tarihi',
        'remaining-amount': 'Kalan Tutar',
        'commission-percentage': 'Prim Yüzdesi',
        'commission-percentage-short': 'Prim %',
        'enter-commission-percentage': 'Prim yüzdesi giriniz',
        'commission-amount-device': 'Prim Tutarı',
        'delivery-status': 'Teslim Durumu',
        'select-delivery-status': 'Teslim durumu seçiniz',
        'pending': 'Beklemede',
        'preparing': 'Hazırlanıyor',
        'shipped': 'Kargoya Verildi',
        'delivered': 'Teslim Edildi',
        'enter-description': 'Açıklama giriniz',
        'device-sales-list': 'Cihaz Satışları Listesi',
        'view-and-manage-all-device-sales': 'Tüm cihaz satışlarını görüntüleyin ve yönetin',
        'commission': 'Prim',
        'total-commission': 'Toplam Komisyon',
        'delete-sale-record': 'Satış Kaydını Sil',
        'are-you-sure-delete-sale-record': 'Bu satış kaydını silmek istediğinize emin misiniz? Bu işlem geri alınamaz.',
        // Roller sayfası çevirileri
        'role-management': 'Rol Yönetimi',
        'manage-system-user-roles': 'Sistem kullanıcı rollerini buradan yönetebilirsiniz',
        'role-list': 'Rol Listesi',
        'add-new-role': 'Yeni Rol Ekle',
        'roles': 'Roller',
        'manage-user-roles-and-permissions': 'Sistemdeki kullanıcı rollerini ve izinlerini yönetin',
        'role-name': 'Rol Adı',
        'creation-date': 'Oluşturulma Tarihi',
        'actions': 'İşlemler',
        'edit': 'Düzenle',
        'delete': 'Sil',
        'are-you-sure-delete-role': 'Bu rolü silmek istediğinizden emin misiniz?',
        'role-permissions-edit': 'Rol İzinlerini Düzenle',
        'permissions': 'İzinler',
        'select-all': 'Tümünü Seç',
        'deselect-all': 'Tümünü Kaldır',
        'view': 'Görüntüle',
        'create': 'Oluştur',
        'load': 'Yükle',
        'query': 'Sorgula',
        'cancel': 'İptal',
        'save': 'Kaydet',
        'saving': 'Kaydediliyor...',
        'role-successfully-deleted': 'Rol başarıyla silindi',
        'error-deleting-role': 'Rol silinirken bir hata oluştu',
        'error-loading-permissions': 'İzinler getirilemedi',
        'error-fetching-permissions': 'İzinler getirilirken bir hata oluştu',
        'role-name-required': 'Rol adı zorunludur',
        'permissions-successfully-updated': 'Rol izinleri başarıyla güncellendi',
        'error-updating-permissions': 'Rol izinleri güncellenirken bir hata oluştu',
        // Modül isimleri çevirileri
        'Panel': 'Panel',
        'Firmalar': 'Firmalar',
        'Bayiler': 'Bayiler',
        'Bakiye-Yonetimi': 'Bakiye Yönetimi',
        'Komisyon-Yonetimi': 'Komisyon Yönetimi',
        'Panel-Kullanicilari': 'Panel Kullanıcıları',
        'Program-Kullanicilari': 'Program Kullanıcıları',
        'Kilometre-Hacker': 'Kilometre Hacker',
        'VIN-Hacker': 'VIN Hacker',
        'Cihaz-Satislari': 'Cihaz Satışları',
        'Cihaz-Satin-Al': 'Cihaz Satın Al',
        'Roller': 'Roller',
        'Raporlar': 'Raporlar',
        'Blog': 'Blog',
        'Ayarlar': 'Ayarlar',
        // Raporlar sayfası çevirileri
        'reports': 'Raporlar',
        'monthly-reports': 'Aylık Raporlar',
        'commission-report': 'Komisyon Raporu',
        'export-to-pdf': 'PDF\'e Aktar',
        'select-company': 'Firma Seçin',
        'all-companies': 'Tüm Firmalar',
        'select-dealer': 'Bayi Seçin',
        'all-dealers': 'Tüm Bayiler',
        'select-month': 'Ay Seçin',
        'select-year': 'Yıl Seçin',
        'january': 'Ocak',
        'february': 'Şubat',
        'march': 'Mart',
        'april': 'Nisan',
        'may': 'Mayıs',
        'june': 'Haziran',
        'july': 'Temmuz',
        'august': 'Ağustos',
        'september': 'Eylül',
        'october': 'Ekim',
        'november': 'Kasım',
        'december': 'Aralık',
        'no-commission-records': 'Henüz komisyon kaydı bulunmuyor',
        'active': 'Aktif',
        'inactive': 'Pasif',
        'total': 'Toplam',
        'total-fee': 'Toplam Ücret',
        'commission': 'Komisyon',
        'balance': 'Bakiye',
        'commission-report-pdf': 'Komisyon Raporu',
        'period': 'Dönem',
        'status': 'Durum',
        'total-fee-pdf': 'Toplam Ucret',
        'total-commission-pdf': 'Toplam Komisyon',
        'current-balance-pdf': 'Guncel Bakiye',
        'page': 'Sayfa',
        'error-fetching-dealers': 'Bayi listesi alınamadı',
        'error-fetching-commission-data': 'Komisyon verileri alınamadı',
        // Blog sayfası çevirileri
        'add-blog': 'Blog Ekle',
        'edit-blog': 'Blog Düzenle',
        'add-edit-blog': 'Blog Ekle/Düzenle',
        'blog-list': 'Blog Listesi',
        'new-blog-entry': 'Yeni Blog Girişi',
        'blog-title': 'Blog Başlığı',
        'enter-blog-title': 'Blog başlığını giriniz',
        'content': 'İçerik',
        'cover-photo': 'Kapak Fotoğrafı',
        'select-photo': 'Fotoğraf Seç',
        'saving': 'Kaydediliyor...',
        'update': 'Güncelle',
        'save': 'Kaydet',
        'cancel': 'İptal',
        'search-by-blog-title': 'Blog başlığına göre ara...',
        'oldest': 'En Eski',
        'newest': 'En Yeni',
        'edit': 'Düzenle',
        'delete': 'Sil',
        'delete-blog': 'Blogu Sil',
        'are-you-sure-delete-blog': 'Bu işlem geri alınamaz.',
        'blog-successfully-added': 'Blog başarıyla eklendi!',
        'blog-successfully-updated': 'Blog başarıyla güncellendi!',
        'blog-successfully-deleted': 'Blog başarıyla silindi',
        'error-loading-blogs': 'Bloglar yüklenirken bir hata oluştu',
        'error-adding-blog': 'Blog eklenirken bir hata oluştu',
        'error-updating-blog': 'Blog güncellenirken bir hata oluştu',
        'error-deleting-blog': 'Blog silinirken bir hata oluştu',
        'please-enter-blog-title': 'Lütfen blog başlığını girin.',
        'please-enter-blog-content': 'Lütfen blog içeriğini girin.',
        'please-select-cover-photo': 'Lütfen bir kapak fotoğrafı seçin.',
        'file-size-too-large': 'Dosya boyutu 5MB\'dan büyük olamaz.',
        'unsupported-file-format': 'Sadece JPEG, PNG, GIF ve WebP formatları desteklenir.',
        'invalid-server-response': 'Sunucudan geçersiz yanıt alındı',
        'network-error': 'Ağ hatası. Bağlantınızı kontrol edin.',
        'unexpected-error': 'Beklenmedik bir hata oluştu',
        // Ayarlar sayfası çevirileri
        'settings': 'Ayarlar',
        'manage-account-settings': 'Hesap ayarlarınızı buradan yönetebilirsiniz',
        'account-settings': 'Hesap Ayarları',
        'location-management': 'Lokasyon Yönetimi',
        'profile-information': 'Profil Bilgileri',
        'basic-account-information': 'Hesabınızla ilgili temel bilgiler',
        'full-name': 'Ad Soyad',
        'email': 'E-posta',
        'role': 'Rol',
        'change-password': 'Şifre Değiştir',
        'update-account-password': 'Hesabınızın şifresini güncelleyin',
        'current-password': 'Mevcut Şifre',
        'new-password': 'Yeni Şifre',
        'confirm-new-password': 'Yeni Şifre (Tekrar)',
        'update-password': 'Şifreyi Güncelle',
        'passwords-do-not-match': 'Yeni şifreler eşleşmiyor',
        'password-updated-successfully': 'Şifreniz başarıyla güncellendi',
        'error-updating-password': 'Şifre değiştirme işlemi başarısız oldu',
        'success': 'Başarılı',
        'error': 'Hata',
        // Lokasyon yönetimi çevirileri
        'province-name-required': 'İl adı gereklidir',
        'district-name-required': 'İlçe adı gereklidir',
        'province-selection-required': 'İl seçimi gereklidir',
        'error-adding-province': 'İl eklenirken bir hata oluştu',
        'province-added-successfully': 'İl başarıyla eklendi',
        'error-adding-district': 'İlçe eklenirken bir hata oluştu',
        'district-added-successfully': 'İlçe başarıyla eklendi',
        'error-deleting-district': 'İlçe silinirken bir hata oluştu',
        'district-deleted-successfully': 'İlçe başarıyla silindi',
        'are-you-sure-delete-district': 'Bu ilçeyi silmek istediğinize emin misiniz?',
        'this-action-cannot-be-undone': 'Bu işlem geri alınamaz.',
        'province': 'İl',
        'district': 'İlçe',
        'add-province': 'İl Ekle',
        'add-district': 'İlçe Ekle',
        'delete-district': 'İlçeyi Sil',
        'province-name': 'İl Adı',
        'district-name': 'İlçe Adı',
        'select-province': 'İl Seçin',
        'enter-province-name': 'İl adını girin',
        'enter-district-name': 'İlçe adını girin',
        'previous': 'Önceki',
        'next': 'Sonraki',
        'no-districts-found': 'Bu il için ilçe bulunamadı',
        'loading': 'Yükleniyor...',
        'cancel': 'İptal',
        'delete': 'Sil',
        'manage-registered-provinces': 'Sistemde kayıtlı illeri yönetin',
        // Profil sayfası çevirileri
        'profile': 'Profil',
        'view-profile-information': 'Profil bilgilerinizi görüntüleyin',
        'profile-information': 'Profil Bilgileri',
        'home': 'Ana Sayfa',
        'status': 'Durum',
        'balance-information': 'Bakiye Bilgileri',
        'dealer-balance': 'Bayi Bakiyesi',
        'all-dealers-balance': 'Tüm Bayilerin Bakiyesi',
        'active-dealer-count': 'Aktif Bayi Sayısı',
        'loading': 'Yükleniyor...',
        'logout': 'Çıkış Yap',
        'language-preference': 'Dil Tercihi',
        'select-language': 'Dil Seçin',
        'language-change-description': 'Dil değişikliği tüm uygulamada geçerli olacaktır',
        'commission-development': 'Komisyon Gelişimi',
        'company-dealer-distribution': 'Firma Bayi Dağılımı',
        'highest-balance-dealers': 'En Yüksek Bakiyeli Bayiler',
        'add-program-user': 'Program Kullanıcı Ekle',
        'select-company-first': 'Önce firma seçiniz',
        'program-user': 'Program Kullanıcı',
        'enter-password': 'Şifre giriniz',
        'enter-new-password': 'Yeni şifre giriniz',
        'first-login': 'İlk Giriş',
        'search-dealer': 'Bayi ara...',
        'dealer-not-found': 'Bayi bulunamadı',
        'mileage-hacker-device': 'Kilometre Hacker Cihazı',
        'mileage-device-description': 'Araçlarınızın kilometre verilerini güvenle tespit edin! İkinci el araç alım-satım süreçlerinde kilometre tespitini hızlı, güvenilir ve doğru bir şekilde yapmanızı sağlayan yenilikçi bir teknolojik çözüm.',
        'vat-included': 'KDV Dahil',
        'buy-now': 'Hemen Satın Al',
        'order-information': 'Sipariş Bilgileri',
        'why-mileage-hacker-device': 'Neden Kilometre Hacker Cihazı?',
        'device-description-1': 'Kilometre Hacker Cihazı, ikinci el araç alım-satım süreçlerinde kilometre tespitini hızlı, güvenilir ve doğru bir şekilde yapmanızı sağlayan yenilikçi bir teknolojik çözümdür. Hem bireysel kullanıcılar hem de profesyonel oto ekspertiz işletmeleri için tasarlanmıştır.',
        'device-description-2': 'Saniyeler içinde araç kilometre verilerini okur ve analiz eder. Motor, ABS, şanzıman, direksiyon ve diğer elektronik sistemlerden kilometre bilgilerini doğrudan okuma özelliğine sahiptir.',
        'device-description-3': 'Basit arayüzü sayesinde herkes tarafından kolayca kullanılabilir. Geniş araç yelpazesiyle uyumlu çalışır ve kapsamlı destek sunar.',
        'who-is-it-for': 'Kimler İçin Uygun?',
        'individual-users': 'Bireysel Kullanıcılar',
        'individual-users-desc': 'İkinci el araç satın almadan önce aracın kilometre geçmişini tespit etmek isteyenler.',
        'auto-expertise-companies': 'Oto Ekspertiz Firmaları',
        'auto-expertise-companies-desc': 'Araç kilometre tespiti hizmetlerini güvenilir bir şekilde sunmayı hedefleyen profesyoneller.',
        'dealers-and-car-companies': 'Galeriler ve Araç Alım-Satım Firmaları',
        'dealers-and-car-companies-desc': 'İş süreçlerini kolaylaştırmak ve müşterilere güvenilir hizmet sağlamak isteyen işletmeler.',
        'device-features': 'Cihaz Özellikleri',
        'feature-1': 'Hatasız veri tespiti ve manipülasyon kontrolü',
        'feature-2': 'Geniş araç yelpazesiyle uyumlu çalışır ve kapsamlı destek sunar',
        'feature-3': 'Saniyeler içinde sonuç alma',
        'feature-4': 'Motor, ABS, şanzıman, direksiyon ve diğer elektronik sistemlerden kilometre bilgilerini doğrudan okuma özelliği',
        'feature-5': 'Profesyonel teknik destek',
        'feature-6': 'Kullanıcı dostu arayüz',
        'feature-7': 'Gelişmiş güvenlik sistemi',
        'feature-8': '1 yıl garanti',
        'feature-9': 'Hızlı işlem süresi',
        'feature-10': 'Güvenli veri analizi',
        'feature-11': '7/24 teknik destek',
        'feature-12': 'Ücretsiz kargo',
        'package-contents': 'Kutu İçeriği',
        'package-item-1': 'Kilometre Hacker OBD Cihazı',
        'package-item-1-desc': 'Ana cihaz',
        'package-item-2': 'WiFi Dongle',
        'package-item-2-desc': 'Kablosuz bağlantı aparatı',
        'package-item-3': 'Kullanım Kılavuzu',
        'package-item-3-desc': 'Detaylı kullanım talimatları',
        'package-item-4': 'Lisans ve Teknik Destek',
        'package-item-4-desc': '1 yıl garantili lisans ve destek',
        'warranty-and-support': 'Garanti ve Teknik Destek',
        'warranty-description': 'Cihazınız 1 yıl boyunca garantilidir. Teknik ekibimiz 7/24 yanınızda olup, WhatsApp üzerinden anlık destek sağlamaktadır. Her yapılan sorgulama için %10 + KDV ücretlendirilirsiniz.',
        'technical-support': 'Teknik Destek',
        'all-time': 'Tüm zamanlar',
        'total-sales-amount': 'Toplam satış tutarı',
        'total-dealer-count': 'Toplam bayi sayısı',
        'dealer-balance': 'Bayi Bakiyesi',
        'all-dealers-balance': 'Tüm bayilerin bakiyesi',
        'total-test-revenue': 'Toplam test geliri',
        'total-company-count': 'Toplam firma sayısı',
        'vin-test-count': 'VIN test sayısı',
        'country': 'Ülke',
        'manage-registered-countries': 'Sistemde kayıtlı ülkeleri yönetin',
        'select-country': 'Ülke seçiniz',
        'delete-province': 'İli Sil',
        'are-you-sure-delete-province': 'ilini silmek istediğinize emin misiniz?',
        'province-deleted-successfully': 'İl başarıyla silindi',
        'error-deleting-province': 'İl silinirken bir hata oluştu',
        'edit-province': 'İli Düzenle',
        'update-province': 'İli Güncelle',
        'province-updated-successfully': 'İl başarıyla güncellendi',
        'error-updating-province': 'İl güncellenirken bir hata oluştu',
        'edit-district': 'İlçeyi Düzenle',
        'update-district': 'İlçeyi Güncelle',
        'district-updated-successfully': 'İlçe başarıyla güncellendi',
        'error-updating-district': 'İlçe güncellenirken bir hata oluştu'
  },
  en: {
    'dashboard': 'Dashboard',
    'vin-hacker': 'VIN Hacker',
    'kilometre-hacker': 'Kilometre Hacker',
    'reports': 'Reports',
    'settings': 'Settings',
    'test-date': 'Test Date',
    'company': 'Company',
    'companies': 'Companies',
    'dealer': 'Dealer',
    'dealers': 'Dealers',
    'module': 'Module',
    'kilometre': 'Mileage',
    'details': 'Details',
    'download': 'Download',
    'close': 'Close',
    'save': 'Save',
    'cancel': 'Cancel',
    'edit': 'Edit',
    'delete': 'Delete',
    'add': 'Add',
    'search': 'Search',
    'filter': 'Filter',
    'export': 'Export',
    'import': 'Import',
    'refresh': 'Refresh',
    'loading': 'Loading...',
    'error': 'Error',
    'success': 'Success',
    'warning': 'Warning',
    'info': 'Info',
    'confirm': 'Confirm',
    'yes': 'Yes',
    'no': 'No',
    'ok': 'OK',
    'back': 'Back',
    'next': 'Next',
    'previous': 'Previous',
    'first': 'First',
    'last': 'Last',
    'page': 'Page',
    'of': 'of',
    'total': 'Total',
    'items': 'items',
    'per-page': 'Per page',
    'showing': 'Showing',
    'to': 'to',
    'entries': 'entries',
    'no-data': 'No data found',
    'no-results': 'No results found',
    'try-again': 'Try again',
    'contact-support': 'Contact support',
    'language': 'Language',
    'turkish': 'Turkish',
    'english': 'English',
    'dashboard-description': 'View system management and statistics here.',
    'total-commission': 'Total Commission',
    'device-sales-total': 'Device Sales Total',
    'total-km-test': 'Total Km Test',
    'active-dealers': 'Active Dealers',
    'total-balance': 'Total Balance',
    'total-test-fee': 'Total Test Fee',
    'active-companies': 'Active Companies',
    'total-vin-test': 'Total VIN Test',
    'panel-users': 'Panel Users',
    'program-users': 'Program Users',
    'balance-management': 'Balance Management',
    'commission-management': 'Commission Management',
    'buy-device': 'Buy Device',
        'roles': 'Roles',
        'blog': 'Blog',
        'logout': 'Logout',
        'device-sales': 'Device Sales',
        'add-company': 'Add New Company',
        'no-companies-found': 'No companies found yet',
        'error-loading-companies': 'Error loading company data',
        'company-name': 'Company Name',
        'company-title': 'Company Title',
        'email': 'Email',
        'phone': 'Phone',
        'tax-office': 'Tax Office',
        'tax-number': 'Tax Number',
        'status': 'Status',
        'active': 'Active',
        'inactive': 'Inactive',
        'companies-description': 'View, edit and manage companies',
        'select-filter': 'Select filter',
        'search-by-company-title': 'Search by company title...',
        'search-by-tax-number': 'Search by tax number...',
    'number': 'No',
    'created-at': 'Created',
        'actions': 'Actions',
        'error-deleting-company': 'Error deleting company',
        'company-deleted-successfully': 'Company deleted successfully',
        'error-loading-data': 'Error loading data',
        'add-new-company': 'Add New Company',
        'add-company-description': 'You can add a new company by entering company information.',
        'company-added-successfully': 'Company added successfully',
        'enter-company-name': 'Enter company name',
        'enter-company-title': 'Enter company title',
        'enter-email-address': 'Enter email address',
        'enter-phone-number': 'Enter phone number',
        'enter-tax-office': 'Enter tax office',
        'enter-tax-number': 'Enter tax number',
        'tc-number': 'TC No',
        'enter-tc-number': 'Enter TC ID number',
        'address': 'Address',
        'enter-address': 'Enter address',
        'iban': 'IBAN',
        'enter-iban-number': 'Enter IBAN number',
        'adding': 'Adding...',
        'dealers-description': 'List of all dealers registered in the system',
        'api-request-failed': 'API request failed',
        'error-deleting-dealer': 'Failed to delete dealer',
        'dealer-deleted-successfully': 'Dealer deleted successfully',
        'search-by-name-or-contact': 'Search by name or contact information...',
        'select-status': 'Select Status',
        'all': 'All',
        'select-company': 'Select Company',
        'all-companies': 'All Companies',
        'add-dealer': 'Add Dealer',
        'dealer-name': 'Dealer Name',
        'city-district': 'City/District',
        'dealer-rate': 'Dealer Rate',
        'no-dealers-found-matching-criteria': 'No dealers found matching search criteria',
        'no-dealers-found': 'No dealers found',
        'delete-dealer': 'Delete Dealer',
        'delete-dealer-confirmation': 'Are you sure you want to delete this dealer? This action cannot be undone.',
        'edit-company': 'Edit Company',
        'error-updating-company': 'Error updating company',
        'company-updated-successfully': 'Company updated successfully',
        'updating': 'Updating...',
        'update': 'Update',
        'delete-company': 'Are you sure you want to delete this company?',
        'delete-company-confirmation': 'This action cannot be undone. The company and all related data will be permanently deleted.',
        'deleting': 'Deleting...',
        'edit-dealer': 'Edit Dealer',
        'add-new-dealer': 'Add New Dealer',
        'fill-dealer-info-completely': 'Please fill in all dealer information completely',
        'dealer-operation-failed': 'Dealer operation failed',
        'dealer-updated-successfully': 'Dealer updated successfully',
        'dealer-added-successfully': 'Dealer added successfully',
        'operation-failed': 'Operation failed',
        'city': 'City',
        'district': 'District',
        'select-city': 'Select City',
        'select-district': 'Select District',
        'select-city-first': 'Select city first',
        'no-districts-found': 'No districts found',
        'saving': 'Saving...',
        'test-based-balance-management-system': 'Test-based balance management system',
        'load-balance': 'Load Balance',
        'online-payment-sipay': 'Online Payment Sipay',
        'balance-history': 'Balance History',
        'balance-loading-completed-successfully': 'Balance loading completed successfully',
        'error-during-balance-loading': 'Error occurred during balance loading',
        'please-fill-all-fields': 'Please fill all fields',
        'enter-valid-amount': 'Enter a valid amount',
        'you-can-load-balance-by-selecting-dealer': 'You can load balance by selecting a dealer',
        'select-dealer': 'Select Dealer',
        'select-company-first': 'Select company first',
        'amount-to-load': 'Amount to Load',
        'enter-amount': 'Enter amount',
        'online-balance-loading-sipay': 'Online Balance Loading Sipay',
        'you-can-load-balance-with-sipay-secure-payment': 'You can load balance with Sipay secure payment infrastructure',
        'amount': 'Amount',
        'processing': 'Processing...',
        'make-payment': 'Make Payment',
        'error-during-payment-process': 'Error occurred while starting payment process',
        'balance-transactions': 'Balance Transactions',
        'date': 'Date',
        'transaction-detail': 'Transaction Detail',
        'description': 'Description',
        'balance': 'Balance',
        'manual-balance-loading': 'Manual Balance Loading',
        'iyzico-balance-loading': 'iyzico Balance Loading',
        'sipay-balance-loading': 'Sipay Balance Loading',
        'no-transactions-found': 'No transactions found',
        'view-edit-and-manage-commission-management': 'View, edit and manage commission management',
        'test-id': 'Test ID',
        'dealer-rate-percentage': 'Dealer Rate (%)',
        'fee': 'Fee',
        'test-commission-amount': 'Test Commission Amount',
        'commission-amount': 'Commission Amount',
        'filtering-successful': 'Filtering successful',
        'error-during-filtering': 'Error occurred during filtering',
        'no-records-found': 'No records found',
        'records': 'records',
        'range': 'range',
        'view-edit-and-manage-panel-users': 'View, edit and manage panel users',
        'search-by-name-or-email': 'Search by name or email...',
        'select-role': 'Select Role',
        'all-roles': 'All Roles',
        'add-user': 'Add User',
        'name': 'Name',
        'role': 'Role',
        'no-users-found-matching-criteria': 'No users found matching search criteria',
        'no-users-found': 'No users found',
        'user-deleted-successfully': 'User deleted successfully',
        'error-deleting-user': 'Error occurred while deleting user',
        'delete-user': 'Delete User',
        'delete-user-confirmation': 'Are you sure you want to delete this user? This action cannot be undone.',
        'panel-user': 'Panel User',
        'fill-required-information-for-panel-user': 'Fill in the required information for the panel user completely.',
        'full-name': 'Full Name',
        'password': 'Password',
        'leave-empty-to-keep-current': 'Leave empty to keep current',
        'language-preference': 'Language Preference',
        'select-language': 'Select Language',
        'user-updated-successfully': 'User updated successfully',
        'user-added-successfully': 'User added successfully',
        'view-edit-and-manage-program-users': 'View, edit and manage program users',
        'search-by-name-or-mac': 'Search by name or MAC address...',
        'all-dealers': 'All Dealers',
        'add-program-user': 'Add Program User',
        'mac-address': 'MAC Address',
        'first-login': 'First Login',
        'no-program-users-found-matching-criteria': 'No program users found matching search criteria',
        'no-program-users-found': 'No program users found',
        'program-user-deleted-successfully': 'Program user deleted successfully',
        'error-deleting-program-user': 'Error occurred while deleting program user',
        'fill-program-user-info-completely': 'Please fill in the program user information completely and correctly',
        'enter-password': 'Enter password',
        'enter-new-password': 'Enter new password',
        'done': 'Done',
        'not-done': 'Not done',
        'program-user-updated-successfully': 'Program user updated successfully',
        'program-user-added-successfully': 'Program user added successfully',
        'cannot-delete-user-with-tests': 'This user cannot be deleted because they have VIN tests. Please delete the tests first or deactivate the user.',
        'user-has-related-data': 'This user cannot be deleted because they have related data.',
        'vehicle-mileage-query-operations': 'You can perform vehicle mileage query operations from here',
        'start-date': 'Start Date',
        'end-date': 'End Date',
        'query': 'Query',
        'plate-model': 'Plate/Model',
        'plate': 'Plate',
        'brand-model': 'Brand/Model',
        'search-by-plate': 'Search by plate...',
        'search-by-brand-model': 'Search by brand/model...',
        'chassis-number': 'Chassis Number',
        'engine-number': 'Engine Number',
        'odometer-km': 'Odometer KM',
        'no-records-found-matching-criteria': 'No records found matching search criteria',
        'date-range': 'Date Range',
        'test-report': 'Test Report',
        'vehicle-information': 'Vehicle Information',
        'test-details': 'Test Details',
        'download-pdf': 'Download PDF',
        'test-type': 'Test Type',
        'test-details-could-not-be-loaded': 'Test details could not be loaded',
        'model-year': 'Model Year',
        'user': 'User',
        'vehicle-vin-and-mileage-query-operations': 'You can perform vehicle VIN and mileage query operations from here',
        'device-sales-management-and-tracking': 'Device sales management and tracking',
        'new-sale': 'New Sale',
        'new-device-sale': 'New Device Sale',
        'edit-device-sale': 'Edit Device Sale',
        'enter-device-sale-information': 'Enter device sale information',
        'total-amount': 'Total Amount',
        'enter-total-amount': 'Enter total amount',
        'paid-amount': 'Paid Amount',
        'enter-paid-amount': 'Enter paid amount',
        'payment-date': 'Payment Date',
        'remaining-payment-date': 'Remaining Payment Date',
        'remaining-amount': 'Remaining Amount',
        'commission-percentage': 'Commission Percentage',
        'commission-percentage-short': 'Commission %',
        'enter-commission-percentage': 'Enter commission percentage',
        'commission-amount-device': 'Commission Amount',
        'delivery-status': 'Delivery Status',
        'select-delivery-status': 'Select delivery status',
        'pending': 'Pending',
        'preparing': 'Preparing',
        'shipped': 'Shipped',
        'delivered': 'Delivered',
        'enter-description': 'Enter description',
        'device-sales-list': 'Device Sales List',
        'view-and-manage-all-device-sales': 'View and manage all device sales',
        'commission': 'Commission',
        'total-commission': 'Total Commission',
        'delete-sale-record': 'Delete Sale Record',
        'are-you-sure-delete-sale-record': 'Are you sure you want to delete this sale record? This action cannot be undone.',
        // Roller sayfası çevirileri
        'role-management': 'Role Management',
        'manage-system-user-roles': 'Manage system user roles from here',
        'role-list': 'Role List',
        'add-new-role': 'Add New Role',
        'roles': 'Roles',
        'manage-user-roles-and-permissions': 'Manage user roles and permissions in the system',
        'role-name': 'Role Name',
        'creation-date': 'Creation Date',
        'actions': 'Actions',
        'edit': 'Edit',
        'delete': 'Delete',
        'are-you-sure-delete-role': 'Are you sure you want to delete this role?',
        'role-permissions-edit': 'Edit Role Permissions',
        'permissions': 'Permissions',
        'select-all': 'Select All',
        'deselect-all': 'Deselect All',
        'view': 'View',
        'create': 'Create',
        'load': 'Load',
        'query': 'Query',
        'cancel': 'Cancel',
        'save': 'Save',
        'saving': 'Saving...',
        'role-successfully-deleted': 'Role successfully deleted',
        'error-deleting-role': 'Error occurred while deleting role',
        'error-loading-permissions': 'Failed to load permissions',
        'error-fetching-permissions': 'Error occurred while fetching permissions',
        'role-name-required': 'Role name is required',
        'permissions-successfully-updated': 'Role permissions successfully updated',
        'error-updating-permissions': 'Error occurred while updating role permissions',
        // Modül isimleri çevirileri
        'Panel': 'Panel',
        'Firmalar': 'Companies',
        'Bayiler': 'Dealers',
        'Bakiye-Yonetimi': 'Balance Management',
        'Komisyon-Yonetimi': 'Commission Management',
        'Panel-Kullanicilari': 'Panel Users',
        'Program-Kullanicilari': 'Program Users',
        'Kilometre-Hacker': 'Kilometre Hacker',
        'VIN-Hacker': 'VIN Hacker',
        'Cihaz-Satislari': 'Device Sales',
        'Cihaz-Satin-Al': 'Buy Device',
        'Roller': 'Roles',
        'Raporlar': 'Reports',
        'Blog': 'Blog',
        'Ayarlar': 'Settings',
        // Raporlar sayfası çevirileri
        'reports': 'Reports',
        'monthly-reports': 'Monthly Reports',
        'commission-report': 'Commission Report',
        'export-to-pdf': 'Export to PDF',
        'select-company': 'Select Company',
        'all-companies': 'All Companies',
        'select-dealer': 'Select Dealer',
        'all-dealers': 'All Dealers',
        'select-month': 'Select Month',
        'select-year': 'Select Year',
        'january': 'January',
        'february': 'February',
        'march': 'March',
        'april': 'April',
        'may': 'May',
        'june': 'June',
        'july': 'July',
        'august': 'August',
        'september': 'September',
        'october': 'October',
        'november': 'November',
        'december': 'December',
        'no-commission-records': 'No commission records found yet',
        'active': 'Active',
        'inactive': 'Inactive',
        'total': 'Total',
        'total-fee': 'Total Fee',
        'commission': 'Commission',
        'balance': 'Balance',
        'commission-report-pdf': 'Commission Report',
        'period': 'Period',
        'status': 'Status',
        'total-fee-pdf': 'Total Fee',
        'total-commission-pdf': 'Total Commission',
        'current-balance-pdf': 'Current Balance',
        'page': 'Page',
        'error-fetching-dealers': 'Failed to fetch dealer list',
        'error-fetching-commission-data': 'Failed to fetch commission data',
        // Blog sayfası çevirileri
        'add-blog': 'Add Blog',
        'edit-blog': 'Edit Blog',
        'add-edit-blog': 'Add/Edit Blog',
        'blog-list': 'Blog List',
        'new-blog-entry': 'New Blog Entry',
        'blog-title': 'Blog Title',
        'enter-blog-title': 'Enter blog title',
        'content': 'Content',
        'cover-photo': 'Cover Photo',
        'select-photo': 'Select Photo',
        'saving': 'Saving...',
        'update': 'Update',
        'save': 'Save',
        'cancel': 'Cancel',
        'search-by-blog-title': 'Search by blog title...',
        'oldest': 'Oldest',
        'newest': 'Newest',
        'edit': 'Edit',
        'delete': 'Delete',
        'delete-blog': 'Delete Blog',
        'are-you-sure-delete-blog': 'This action cannot be undone.',
        'blog-successfully-added': 'Blog successfully added!',
        'blog-successfully-updated': 'Blog successfully updated!',
        'blog-successfully-deleted': 'Blog successfully deleted',
        'error-loading-blogs': 'Error loading blogs',
        'error-adding-blog': 'Error adding blog',
        'error-updating-blog': 'Error updating blog',
        'error-deleting-blog': 'Error deleting blog',
        'please-enter-blog-title': 'Please enter blog title.',
        'please-enter-blog-content': 'Please enter blog content.',
        'please-select-cover-photo': 'Please select a cover photo.',
        'file-size-too-large': 'File size cannot be larger than 5MB.',
        'unsupported-file-format': 'Only JPEG, PNG, GIF and WebP formats are supported.',
        'invalid-server-response': 'Invalid response from server',
        'network-error': 'Network error. Please check your connection.',
        'unexpected-error': 'An unexpected error occurred',
        // Ayarlar sayfası çevirileri
        'settings': 'Settings',
        'manage-account-settings': 'Manage your account settings here',
        'account-settings': 'Account Settings',
        'location-management': 'Location Management',
        'profile-information': 'Profile Information',
        'basic-account-information': 'Basic information about your account',
        'full-name': 'Full Name',
        'email': 'Email',
        'role': 'Role',
        'change-password': 'Change Password',
        'update-account-password': 'Update your account password',
        'current-password': 'Current Password',
        'new-password': 'New Password',
        'confirm-new-password': 'New Password (Confirm)',
        'update-password': 'Update Password',
        'passwords-do-not-match': 'New passwords do not match',
        'password-updated-successfully': 'Password updated successfully',
        'error-updating-password': 'Password change operation failed',
        'success': 'Success',
        'error': 'Error',
        // Lokasyon yönetimi çevirileri
        'province-name-required': 'Province name is required',
        'district-name-required': 'District name is required',
        'province-selection-required': 'Province selection is required',
        'error-adding-province': 'Error adding province',
        'province-added-successfully': 'Province added successfully',
        'error-adding-district': 'Error adding district',
        'district-added-successfully': 'District added successfully',
        'error-deleting-district': 'Error deleting district',
        'district-deleted-successfully': 'District deleted successfully',
        'are-you-sure-delete-district': 'Are you sure you want to delete this district?',
        'this-action-cannot-be-undone': 'This action cannot be undone.',
        'province': 'Province',
        'district': 'District',
        'add-province': 'Add Province',
        'add-district': 'Add District',
        'delete-district': 'Delete District',
        'province-name': 'Province Name',
        'district-name': 'District Name',
        'select-province': 'Select Province',
        'enter-province-name': 'Enter province name',
        'enter-district-name': 'Enter district name',
        'previous': 'Previous',
        'next': 'Next',
        'no-districts-found': 'No districts found for this province',
        'loading': 'Loading...',
        'cancel': 'Cancel',
        'delete': 'Delete',
        'manage-registered-provinces': 'Manage registered provinces in the system',
        // Profil sayfası çevirileri
        'profile': 'Profile',
        'view-profile-information': 'View your profile information',
        'profile-information': 'Profile Information',
        'home': 'Home',
        'status': 'Status',
        'balance-information': 'Balance Information',
        'dealer-balance': 'Dealer Balance',
        'all-dealers-balance': 'All Dealers Balance',
        'active-dealer-count': 'Active Dealer Count',
        'loading': 'Loading...',
        'logout': 'Logout',
        'language-preference': 'Language Preference',
        'select-language': 'Select Language',
        'language-change-description': 'Language change will be applied throughout the application',
        'commission-development': 'Commission Development',
        'company-dealer-distribution': 'Company Dealer Distribution',
        'highest-balance-dealers': 'Highest Balance Dealers',
        'add-program-user': 'Add Program User',
        'select-company-first': 'Select company first',
        'program-user': 'Program User',
        'enter-password': 'Enter password',
        'enter-new-password': 'Enter new password',
        'first-login': 'First Login',
        'search-dealer': 'Search dealer...',
        'dealer-not-found': 'Dealer not found',
        'mileage-hacker-device': 'Mileage Hacker Device',
        'mileage-device-description': 'Safely detect your vehicle\'s mileage data! An innovative technological solution that enables you to perform mileage detection quickly, reliably and accurately in second-hand vehicle buying and selling processes.',
        'vat-included': 'VAT Included',
        'buy-now': 'Buy Now',
        'order-information': 'Order Information',
        'why-mileage-hacker-device': 'Why Mileage Hacker Device?',
        'device-description-1': 'The Mileage Hacker Device is an innovative technological solution that enables you to perform mileage detection quickly, reliably and accurately in second-hand vehicle buying and selling processes. It is designed for both individual users and professional auto expertise businesses.',
        'device-description-2': 'It reads and analyzes vehicle mileage data in seconds. It has the ability to directly read mileage information from engine, ABS, transmission, steering and other electronic systems.',
        'device-description-3': 'Thanks to its simple interface, it can be easily used by everyone. It works compatibly with a wide range of vehicles and provides comprehensive support.',
        'who-is-it-for': 'Who Is It For?',
        'individual-users': 'Individual Users',
        'individual-users-desc': 'Those who want to detect the mileage history of the vehicle before buying a second-hand vehicle.',
        'auto-expertise-companies': 'Auto Expertise Companies',
        'auto-expertise-companies-desc': 'Professionals who aim to provide vehicle mileage detection services reliably.',
        'dealers-and-car-companies': 'Dealers and Car Trading Companies',
        'dealers-and-car-companies-desc': 'Businesses that want to facilitate business processes and provide reliable service to customers.',
        'device-features': 'Device Features',
        'feature-1': 'Error-free data detection and manipulation control',
        'feature-2': 'Works compatibly with a wide range of vehicles and provides comprehensive support',
        'feature-3': 'Get results in seconds',
        'feature-4': 'Direct reading capability of mileage information from engine, ABS, transmission, steering and other electronic systems',
        'feature-5': 'Professional technical support',
        'feature-6': 'User-friendly interface',
        'feature-7': 'Advanced security system',
        'feature-8': '1 year warranty',
        'feature-9': 'Fast processing time',
        'feature-10': 'Secure data analysis',
        'feature-11': '24/7 technical support',
        'feature-12': 'Free shipping',
        'package-contents': 'Package Contents',
        'package-item-1': 'Mileage Hacker OBD Device',
        'package-item-1-desc': 'Main device',
        'package-item-2': 'WiFi Dongle',
        'package-item-2-desc': 'Wireless connection device',
        'package-item-3': 'User Manual',
        'package-item-3-desc': 'Detailed usage instructions',
        'package-item-4': 'License and Technical Support',
        'package-item-4-desc': '1 year guaranteed license and support',
        'warranty-and-support': 'Warranty and Technical Support',
        'warranty-description': 'Your device is guaranteed for 1 year. Our technical team is with you 24/7 and provides instant support via WhatsApp. You are charged 10% + VAT for each query made.',
        'technical-support': 'Technical Support',
        'all-time': 'All time',
        'total-sales-amount': 'Total sales amount',
        'total-dealer-count': 'Total dealer count',
        'dealer-balance': 'Dealer Balance',
        'all-dealers-balance': 'All dealers balance',
        'total-test-revenue': 'Total test revenue',
        'total-company-count': 'Total company count',
        'vin-test-count': 'VIN test count',
        'country': 'Country',
        'manage-registered-countries': 'Manage registered countries',
        'select-country': 'Select country',
        'delete-province': 'Delete Province',
        'are-you-sure-delete-province': 'Are you sure you want to delete this province?',
        'province-deleted-successfully': 'Province deleted successfully',
        'error-deleting-province': 'Error deleting province',
        'edit-province': 'Edit Province',
        'update-province': 'Update Province',
        'province-updated-successfully': 'Province updated successfully',
        'error-updating-province': 'Error updating province',
        'edit-district': 'Edit District',
        'update-district': 'Update District',
        'district-updated-successfully': 'District updated successfully',
        'error-updating-district': 'Error updating district'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('tr');
  const { user } = useAuth(); // Kullanıcı durumunu takip et
  
  console.log('🚀 LanguageProvider rendered with language:', language);
  console.log('🚀 LanguageProvider children:', children);
  console.log('🚀 LanguageProvider user:', user);
  
  const t = (key: string) => translations[language][key] || key;
  
  // Kullanıcı dil tercihini yükle - kullanıcı giriş yaptıktan sonra
  useEffect(() => {
    console.log('LanguageContext useEffect triggered, user:', user);
    
    if (!user) {
      console.log('No user, keeping default language: tr');
      return;
    }
    
    const loadUserLanguage = async () => {
      try {
        console.log('Fetching user data for language preference...');
        const response = await fetch('/api/user');
        if (response.ok) {
          const userData = await response.json();
          console.log('User data received:', userData);
          console.log('User object:', userData.user);
          console.log('Language preference:', userData.user?.language_preference);
          
          // API response'u kontrol et - userData.user veya userData.language_preference
          const userObj = userData.user || userData;
          const languagePref = userObj?.language_preference;
          
          console.log('Processed user object:', userObj);
          console.log('Processed language preference:', languagePref);
          
          if (userObj && languagePref) {
            console.log('Loading user language preference:', languagePref);
            const newLanguage = languagePref as Language;
            console.log('Setting language to:', newLanguage);
            setLanguage(newLanguage);
          } else {
            console.log('No language preference found or user not found');
          }
        } else {
          console.log('Failed to fetch user data, status:', response.status);
        }
      } catch (error) {
        console.error('Failed to load user language preference:', error);
      }
    };

    loadUserLanguage();
  }, [user]); // user değiştiğinde çalış

  // Debug için language değişikliklerini logla
  useEffect(() => {
    console.log('Language changed to:', language);
  }, [language]);
  
  // Dil tercihini kaydetme fonksiyonu
  const saveLanguagePreference = async (newLanguage: Language) => {
    try {
      await fetch('/api/panel-users/language', {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ language: newLanguage })
      });
    } catch (error) {
      console.error('Failed to save language preference:', error);
    }
  };
  
  const handleLanguageChange = (newLanguage: Language) => {
    setLanguage(newLanguage);
    saveLanguagePreference(newLanguage);
  };
  
  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleLanguageChange, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
